development:
  adapter: postgresql
  database: apato_development 
  username: twofold
  password: e19
  host: localhost
  min_messages: warning

test:
  adapter: postgresql
  database: apato_test 
  username: twofold
  password: e19
  host: localhost
  min_messages: warning

production:
  adapter: postgresql
  database: apato_production
  username: twofold
  password: e19
  host: localhost
  min_messages: warning